// GENERATED by scripts/gen-assets.mjs. Do not edit.
// Regenerated before every build, so this always reflects what is in public/.
//
// Checked: avatar.glb, Atishay_Jain_Resume.pdf
export const hasAvatar = false;
export const hasResume = true;
