// src/content/oss.ts
// Typed access to the upstream contribution snapshot in oss-data.json.
//
// The JSON is generated by scripts/fetch-oss.mjs and committed. Nothing here
// invents or rounds anything: every row came from the GitHub search API, and
// `fetchedAt` says when.

import raw from "./oss-data.json";

export type PrState = "merged" | "open" | "closed";

export type OssPr = {
  number: number;
  title: string;
  url: string;
  state: PrState;
  created: string;
  closedAt: string | null;
};

export type OssRepo = {
  full: string;
  owner: string;
  name: string;
  slug: string;
  merged: number;
  open: number;
  closed: number;
  prs: OssPr[];
};

export type OssData = {
  user: string;
  fetchedAt: string;
  note: string;
  totals: { merged: number; open: number; closed: number; prs: number };
  repoCount: number;
  repos: OssRepo[];
};

export const oss = raw as OssData;

/** Repos with at least one merged PR, best first. These are the record. */
export const mergedRepos: OssRepo[] = oss.repos.filter((r) => r.merged > 0);

/** Everything else: open or closed, nothing landed yet. */
export const pendingRepos: OssRepo[] = oss.repos.filter((r) => r.merged === 0);

export function getRepo(slug: string): OssRepo | undefined {
  return oss.repos.find((r) => r.slug === slug);
}

export function repoSlugs(): string[] {
  return oss.repos.map((r) => r.slug);
}

/**
 * Hand-written context for a project, shown on its page above the PR list.
 * Deliberately sparse: a repo with nothing written about it shows only the
 * verified PR list, which is still true. An invented description of what
 * cilium does would be worse than none.
 */
export const REPO_NOTES: Record<string, string> = {};
