// scripts/gen-assets.mjs
// Writes src/content/assets.ts with what actually exists in public/.
//
// Why generated rather than checked at render time: the pages that need to
// know are client components, and importing node:fs into one pulls it into the
// browser bundle. A 404 inside a WebGL canvas renders as a silent empty box,
// which looks identical to a broken scene, so the page has to know BEFORE it
// mounts anything.
//
// Runs automatically before every build (prebuild).

import fs from "node:fs";
import path from "node:path";

const PUBLIC = path.join(process.cwd(), "public");
const OUT = path.join(process.cwd(), "src", "content", "assets.ts");

const files = {
  hasAvatar: "avatar.glb",
  hasResume: "Atishay_Jain_Resume.pdf",
};

const found = Object.fromEntries(
  Object.entries(files).map(([key, name]) => {
    const p = path.join(PUBLIC, name);
    const ok = fs.existsSync(p) && fs.statSync(p).isFile() && fs.statSync(p).size > 0;
    return [key, ok];
  })
);

const body = `// GENERATED by scripts/gen-assets.mjs. Do not edit.
// Regenerated before every build, so this always reflects what is in public/.
//
// Checked: ${Object.values(files).join(", ")}
${Object.entries(found)
  .map(([k, v]) => `export const ${k} = ${v};`)
  .join("\n")}
`;

fs.writeFileSync(OUT, body);
for (const [k, v] of Object.entries(found)) {
  console.log(`  ${k}: ${v}${v ? "" : `  (public/${files[k]} not found)`}`);
}
